version: "3.7"

services:
    utekai:
        build: .
        env_file:
            - .env
        ports:
            - "9292:443"
        volumes:
            - ./credentials:/credentials
    postgres:
        image: postgres:12.2-alpine
        ports:
            - "5432:5432"
        expose:
            - "5432"
        env_file:
            - .env
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ./postgres:/docker-entrypoint-initdb.d
            - ./dbdata:/var/lib/postgresql/data

