version: "3.7"

services:
    utekai:
        # restart: always
        build: .
        env_file:
            - .env
        volumes:
            - ./credentials:/credentials
            - ./images:/images
    postgres:
        image: postgres:12.2-alpine
        expose:
            - "5432"
        env_file:
            - .env
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ./postgres:/docker-entrypoint-initdb.d
            - ./dbdata:/var/lib/postgresql/data

